"""Initial migration

Revision ID: 331e4efb0f4b
Revises: d27cfa63ad6a
Create Date: 2025-03-25 09:46:26.557114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331e4efb0f4b'
down_revision: Union[str, None] = 'd27cfa63ad6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['entry.uuid'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.add_column('users', sa.Column('banned', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    op.drop_table('reports')
    # ### end Alembic commands ###
