"""updated transactions

Revision ID: 625929bfb630
Revises: 5bcd2937ec27
Create Date: 2025-03-02 11:03:29.954398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625929bfb630'
down_revision: Union[str, None] = '5bcd2937ec27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updatedAt')
    op.drop_column('transactions', 'createdAt')
    # ### end Alembic commands ###
