"""Initial migration

Revision ID: 6346f05ac3b6
Revises: a80b627116e4
Create Date: 2025-03-05 19:53:35.954662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6346f05ac3b6'
down_revision: Union[str, None] = 'a80b627116e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('negotiable', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'negotiable')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
