"""Initial migration

Revision ID: 8f7b7deeb0c0
Revises: 331e4efb0f4b
Create Date: 2025-03-25 10:25:32.653591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7b7deeb0c0'
down_revision: Union[str, None] = '331e4efb0f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'updatedAt')
    op.drop_column('reports', 'createdAt')
    # ### end Alembic commands ###
