"""Initial migration

Revision ID: ac15d46f6ca9
Revises: f21d13142734
Create Date: 2025-03-04 18:17:14.081935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac15d46f6ca9'
down_revision: Union[str, None] = 'f21d13142734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'entry', ['uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###
