"""Initial migration

Revision ID: b7737ef3d1a9
Revises: 8f7b7deeb0c0
Create Date: 2025-03-25 11:20:15.069278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7737ef3d1a9'
down_revision: Union[str, None] = '8f7b7deeb0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_product_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['chat_id'], ondelete='CASCADE')
    op.drop_constraint('reports_product_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transactions_product_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_product_id_fkey', 'transactions', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_product_id_fkey', 'reports', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['chat_id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_product_id_fkey', 'chats', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
