"""Initial migration

Revision ID: f21d13142734
Revises: 66ffbbdf328f
Create Date: 2025-03-04 18:00:43.364632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21d13142734'
down_revision: Union[str, None] = '66ffbbdf328f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_new_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_entry_email'), 'entry', ['email'], unique=True)
    op.create_index(op.f('ix_entry_uuid'), 'entry', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_uuid'), table_name='entry')
    op.drop_index(op.f('ix_entry_email'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
